# Generated by Django 3.0 on 2019-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonarticle',
            name='header',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='header'),
        ),
    ]
