# Generated by Django 3.0 on 2019-12-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_agent', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalThemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('body_article', models.TextField()),
                ('global_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.GlobalThemeModel')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2048)),
                ('answer', models.CharField(max_length=512)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.SubtopicModel')),
            ],
        ),
    ]
