# Generated by Django 3.0 on 2019-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banusermodel',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='banusermodel',
            name='ip_agent',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
